package ai.timefold.solver.core.impl.evolutionaryalgorithm.population;

import java.util.List;

import ai.timefold.solver.core.api.score.Score;
import ai.timefold.solver.core.impl.evolutionaryalgorithm.context.IndividualGenerator;
import ai.timefold.solver.core.impl.evolutionaryalgorithm.decider.EvolutionaryDecider;

import org.jspecify.annotations.Nullable;

/**
 * Basic representation of a population,
 * including individuals and additional information generated by the {@link EvolutionaryDecider evolutionary strategy},
 * such as diversity rate and groups of feasible and infeasible individuals.
 */
public interface Population<Solution_, Score_ extends Score<Score_>> extends IndividualGenerator<Solution_, Score_> {

    /**
     * @return all individuals who are currently included in the population.
     */
    List<Individual<Solution_, Score_>> getAllIndividuals();

    /**
     * Add a new individual to the population
     * 
     * @param individual the individual to be added
     * @return true if the best individual is updated; false otherwise
     */
    boolean addIndividual(Individual<Solution_, Score_> individual);

    /**
     * Select an individual from the population.
     * Different strategies, such as binary tournament selection, can be used to choose the individual.
     * 
     * @return an individual from the population.
     */
    Individual<Solution_, Score_> selectIndividual();

    /**
     * @return the current best individual or null otherwise.
     */
    @Nullable
    Individual<Solution_, Score_> getBestIndividual();
}
